name: Demo Event
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
  push:
    branches:
     - 'daily/**'
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: npm test