name: Demo Event
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dependencies
        run: npm ci