name: Demo Event
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Dependencies
        run: npm ci